[tool.uv.workspace]
members = [
    "packages/core",
    "packages/cli",
    "packages/crypt",
    "packages/google",
    "packages/sqlite",
]

[tool.uv.sources]
wcpan-drive-core = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
