[project]
name = "wcpan-drive-cli"
version = "3.9.0"
description = "command line tool for wcpan.drive"
readme = "README.md"
license = "MIT"
authors = [
    {name = "Wei-Cheng Pan", email = "legnaleurc@gmail.com"}
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = [
    "PyYAML>=6.0.1",
    "wcpan-drive-core>=4.1.0",
    "wcpan-logging>=2.0.3",
    "wcpan-queue>=7.2.1",
    "python-magic>=0.4.27",
    "pymediainfo>=7.0.1",
]

[project.scripts]
"wcpan.drive.cli" = "wcpan.drive.cli._main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["wcpan"]
